# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!


target 'DwangoHack_Sub_D' do

pod 'Alamofire'
pod 'SwiftyJSON'

end

target 'DwangoHack_Sub_DTests' do

end

target 'DwangoHack_Sub_DUITests' do

end

